project_name: zd-tilt
builds:
- main: ./cmd/tilt/main.go
  binary: zd-tilt
  id: tilt-darwin
  flags:
  - -tags=osusergo
  - -mod=vendor
  goos:
  - darwin
  goarch:
  - amd64
  - arm64
  env:
  # Compiles against the MacOS FSEvents system libraries.
  - CGO_ENABLED=1
  - CC=/osxcross/target/bin/x86_64h-apple-darwin20.2-clang
archives:
- name_template: "{{ .ProjectName }}.{{ .Version }}.{{ .Os }}.{{ .Arch }}"
  replacements:
    windows: windows
    darwin: mac
    linux: linux
    386: i386
    amd64: x86_64
    arm: arm_ALPHA
    arm64: arm64_ALPHA
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs?:'
    - '^tests?:'
    - '^cleanup:'
    - '^circleci:'
    - '^ci:'
release:
  github:
    owner: zendesk
    name: tilt
brews:
- tap:
    owner: zendesk
    name: homebrew-devops
  commit_author:
    name: Tilt Dev
    email: hi@tilt.dev
  folder: Formula
  url_template: "https://github.com/zendesk/tilt/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  homepage: "https://tilt.dev/"
  description: "Tilt powers multi-service developments for teams that deploy to Kubernetes."
  test: |
    system "#{bin}/zd-tilt version"
    system "#{bin}/zd-tilt verify-install"

# Uncomment these lines if you want to experiment with other
# parts of the release process without releasing new binaries.
# release:
#  disable: true
